export const ADD_LIST = 'ADD_LIST'
export const GET_LISTS = 'GET_LISTS'
export const SET_LIST_ID_TO_DELETE = 'SET_LIST_ID_FOR_DELETE'
export const GET_LIST_BY_ID = 'GET_LIST_BY_ID'
export const DELETE_LIST = 'DELETE_LIST'